import { ClerkProvider } from "@clerk/nextjs"
import { Inter } from "next/font/google"
import { Metadata } from "next";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "../api/uploadthing/core";

import '../globals.css'

import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Auth",
    description: "Generated by create next app",
};

export default function RootLayout({
    children
}: {
    children: React.ReactNode
}) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={`${inter.className} bg-dark-1`}>
                    <NextSSRPlugin

                        routerConfig={extractRouterConfig(ourFileRouter)}
                    />
                    {children}
                </body>
            </html>
        </ClerkProvider>
    )
}